server:
  port: 10006
  servlet:
    context-path: /
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
spring:
  datasource:
    url: jdbc:postgresql://8.142.78.63:5432/kong
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  unauthorizedUrl: /unauthorizedurl
  web:
    enabled: true
  successUrl: /index
  loginUrl: /login

